### PR TITLE
fix md lists without indent multiples of 4

### PR DESCRIPTION
**Pull request by ahwagner**
addresses #98

### CODE REVIEW

**Comment by reece** [comment]
Would you be open to just indenting 4 spaces everywhere? 4 spaces is the intended spec, even if followed poorly. And, it's also easier to read and consistent with most of the HGVS Nomenclature markdown.

Sigh... we ended up with the mix of indents because I was using prettier as a pre-commit hook. It was rewriting markdown lists to make them *two* spaces because that what it wants. In fact, the author is so insistent that prettier should NOT be configurable. So, that makes prettier incompatible with intended markdown AFAICT. My intention was to make it 4 spaces everywhere.

**Comment by ahwagner** [comment]
@reece I agree. I suggested in https://github.com/HGVSnomenclature/hgvs-nomenclature/issues/98#issuecomment-1826463614 that we use this as a short-term work-around while we fix the indent issue; I also am leaning towards compliance with markdown convention.

This is a minimal effort solution and I won't lose any sleep over it if you want to close the PR and just go straight to adjusting the linter. Or we can merge this and push that effort out for another day if we have other more pressing issues.

**Comment by reece** [comment]
Check out this alternative: https://github.com/HGVSnomenclature/hgvs-nomenclature/pull/101

**Comment by reece** [comment]
I merged the indentation fix since that seemed to be the direction @ahwagner wanted to go also

**Pull request closed without merging**
