### PR TITLE
Update contrib guide

### PR DESCRIPTION
**Pull request by ahwagner**
Adds text drafted by @marinadistefano and reviewed by HVNC.

### CODE REVIEW

**Comment by marinadistefano** [comment]
This looks good to me! Thanks @ahwagner

**Review by reece — APPROVED** [review]

**Comment by ifokkema** [comment]
This also adds a reference to a method to ask us a question on GitHub:
> You may also submit questions to our
[GitHub repository Q&A board](<https://github.com/HGVSnomenclature/hgvs-nomenclature/discussions/new?category=q-a>).

Is it a good idea to offer multiple methods for this? Is one preferred over the other? Does the deadline that we set for ourselves also count for the GitHub method of asking us a question?

**Comment by marinadistefano** [comment]
Yeah, I do have concerns about missing something that it on our GitHub Q&A board instead of via email.

**Comment by reece** [comment]
Ah. FWIW, I read the PR as this already being approved by the HVNC so didn't comment.

If it's still up for discussion, then 1) I agree that we should drop the Q&A board, 2) I think the text about the mailing list usage, turn around time, etc. is far too long. (Preview at https://hgvs-nomenclature.org/main/).

I recommend:
- merging the first two paragraphs ("Join the..." and "Messages sent to...").
- dropping the entire "When members of the community..." paragraph
- dropping the Q&A board paragraph

Also, in a separate PR, I proposed to rename this section and add a new announcement-only group. See https://hgvs-nomenclature--191.org.readthedocs.build/191/.

**Comment by reece** [comment]
Please continue the conversation on #194

**Pull request merged**
