### PR TITLE
Fix styling issues, mainly with the Q&A sections and indenting in the source code

### LINKED ISSUE #84: Fix styling in general.md
The questions in general.md are plain text. Highlight the question, perhaps with admonitions or definition lists.

### PR DESCRIPTION
**Pull request by ifokkema**
~~This branch was branched off of `fix/typos` to prevent conflicts, but this means PR #119 needs to be merged first before this can be merged. Otherwise, this PR includes those changes, too.~~ Ready for review!

- Fixed indentation for lists in several files.
- Fix the DNA deletion page completely; fixed problems with indentation, backticks closed by single quotes, and underscores in variant descriptions escaped with a backslash.
- Fixed all the styling of all the Q&A sections. Some were rendered as lists, others had the answers rendered as code.
- Anchors should be closed, otherwise, the page renders a link.

Closes #84, #103, #106, #117.

### CODE REVIEW

**Review by reece — COMMENTED** [review]
Thank you for fixing all of the backtick issues. Writing regexps to transform these pages was quite challenging!

**Comment by reece** [comment]
@ifokkema : Because I had already reviewed this PR, I didn't get another notice. However, I  see that you did a bunch of work. I'll review on the 26th.

**Comment by ifokkema** [comment]
@reece Ah, no worries! I hope you had a great Christmas!
If you have time, let me know if you'd like me to proceed as discussed earlier per email (Dec 7th); I have no problem making the changes; my only worry is that the PR will become illegible. If you don't mind that, I'll get onto it.

**Review by reece — APPROVED** [review]
This looks good to me. Thanks again for cleaning up the minor mess that I left here.

**Pull request merged**
